# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.api.certificates_api import CertificatesApi


class TestCertificatesApi(unittest.TestCase):
    """CertificatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CertificatesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_certificates_get(self) -> None:
        """Test case for v1_certificates_get

        List certificates
        """
        pass

    def test_v1_certificates_upload_post(self) -> None:
        """Test case for v1_certificates_upload_post

        Upload P12 certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
