# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.invoice_item import InvoiceItem

class TestInvoiceItem(unittest.TestCase):
    """InvoiceItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceItem:
        """Test InvoiceItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceItem`
        """
        model = InvoiceItem()
        if include_optional:
            return InvoiceItem(
                code = 'PROD001',
                description = 'Servicio de consultoría',
                quantity = 1,
                unit_price = 10000,
                discount = 0,
                tax_code = '2'
            )
        else:
            return InvoiceItem(
                description = 'Servicio de consultoría',
                quantity = 1,
                unit_price = 10000,
                tax_code = '2',
        )
        """

    def testInvoiceItem(self):
        """Test InvoiceItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
