# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.health_response import HealthResponse

class TestHealthResponse(unittest.TestCase):
    """HealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthResponse:
        """Test HealthResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthResponse`
        """
        model = HealthResponse()
        if include_optional:
            return HealthResponse(
                status = 'healthy',
                name = '',
                version = '',
                environment = '',
                docs = '',
                checks = ecuapi.models.health_response_checks.HealthResponse_checks(
                    api = '', 
                    database = '', 
                    storage = '', ),
                timestamp = ''
            )
        else:
            return HealthResponse(
                status = 'healthy',
        )
        """

    def testHealthResponse(self):
        """Test HealthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
