# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.authorize_invoice_response import AuthorizeInvoiceResponse

class TestAuthorizeInvoiceResponse(unittest.TestCase):
    """AuthorizeInvoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorizeInvoiceResponse:
        """Test AuthorizeInvoiceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizeInvoiceResponse`
        """
        model = AuthorizeInvoiceResponse()
        if include_optional:
            return AuthorizeInvoiceResponse(
                data = ecuapi.models.authorize_invoice_response_data.AuthorizeInvoiceResponse_data(
                    id = '', 
                    status = '', 
                    sri_response = null, )
            )
        else:
            return AuthorizeInvoiceResponse(
                data = ecuapi.models.authorize_invoice_response_data.AuthorizeInvoiceResponse_data(
                    id = '', 
                    status = '', 
                    sri_response = null, ),
        )
        """

    def testAuthorizeInvoiceResponse(self):
        """Test AuthorizeInvoiceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
