# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.send_invoice_response_data import SendInvoiceResponseData

class TestSendInvoiceResponseData(unittest.TestCase):
    """SendInvoiceResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendInvoiceResponseData:
        """Test SendInvoiceResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendInvoiceResponseData`
        """
        model = SendInvoiceResponseData()
        if include_optional:
            return SendInvoiceResponseData(
                id = '',
                access_key = '',
                status = '',
                sri_response = None
            )
        else:
            return SendInvoiceResponseData(
                id = '',
                access_key = '',
                status = '',
        )
        """

    def testSendInvoiceResponseData(self):
        """Test SendInvoiceResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
