# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.authorize_invoice_response_data import AuthorizeInvoiceResponseData

class TestAuthorizeInvoiceResponseData(unittest.TestCase):
    """AuthorizeInvoiceResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorizeInvoiceResponseData:
        """Test AuthorizeInvoiceResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizeInvoiceResponseData`
        """
        model = AuthorizeInvoiceResponseData()
        if include_optional:
            return AuthorizeInvoiceResponseData(
                id = '',
                status = '',
                sri_response = None
            )
        else:
            return AuthorizeInvoiceResponseData(
                id = '',
                status = '',
        )
        """

    def testAuthorizeInvoiceResponseData(self):
        """Test AuthorizeInvoiceResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
