# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.invoice_detail_response_data import InvoiceDetailResponseData

class TestInvoiceDetailResponseData(unittest.TestCase):
    """InvoiceDetailResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceDetailResponseData:
        """Test InvoiceDetailResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceDetailResponseData`
        """
        model = InvoiceDetailResponseData()
        if include_optional:
            return InvoiceDetailResponseData(
                id = '',
                organization_id = '',
                status = '',
                type = '',
                subtotal = 1.337,
                tax_amount = 1.337,
                total_amount = 1.337,
                access_key = '',
                recipient_name = '',
                recipient_id = '',
                recipient_phone = '',
                created_at = '',
                updated_at = '',
                items = [
                    null
                    ]
            )
        else:
            return InvoiceDetailResponseData(
                id = '',
                organization_id = '',
                status = '',
                type = '',
                subtotal = 1.337,
                tax_amount = 1.337,
                total_amount = 1.337,
                access_key = '',
                recipient_name = '',
                recipient_id = '',
                recipient_phone = '',
                created_at = '',
                updated_at = '',
                items = [
                    null
                    ],
        )
        """

    def testInvoiceDetailResponseData(self):
        """Test InvoiceDetailResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
