# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.api.invoices_api import InvoicesApi


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_invoices_get(self) -> None:
        """Test case for v1_invoices_get

        List invoices
        """
        pass

    def test_v1_invoices_id_authorize_post(self) -> None:
        """Test case for v1_invoices_id_authorize_post

        Authorize invoice
        """
        pass

    def test_v1_invoices_id_delete(self) -> None:
        """Test case for v1_invoices_id_delete

        Void invoice
        """
        pass

    def test_v1_invoices_id_get(self) -> None:
        """Test case for v1_invoices_id_get

        Get invoice by ID
        """
        pass

    def test_v1_invoices_id_pdf_get(self) -> None:
        """Test case for v1_invoices_id_pdf_get

        Download RIDE PDF
        """
        pass

    def test_v1_invoices_id_send_post(self) -> None:
        """Test case for v1_invoices_id_send_post

        Send invoice to SRI
        """
        pass

    def test_v1_invoices_id_xml_get(self) -> None:
        """Test case for v1_invoices_id_xml_get

        Download signed XML
        """
        pass

    def test_v1_invoices_post(self) -> None:
        """Test case for v1_invoices_post

        Create invoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
