# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.create_invoice_response import CreateInvoiceResponse

class TestCreateInvoiceResponse(unittest.TestCase):
    """CreateInvoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInvoiceResponse:
        """Test CreateInvoiceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInvoiceResponse`
        """
        model = CreateInvoiceResponse()
        if include_optional:
            return CreateInvoiceResponse(
                data = ecuapi.models.create_invoice_response_data.CreateInvoiceResponse_data(
                    id = '', 
                    subtotal = 1.337, 
                    tax_amount = 1.337, 
                    total = 1.337, 
                    status = '', ),
                meta = ecuapi.models.meta.Meta(
                    request_id = '', 
                    timestamp = '', 
                    page = 1.337, 
                    per_page = 1.337, 
                    total = 1.337, 
                    total_pages = 1.337, )
            )
        else:
            return CreateInvoiceResponse(
                data = ecuapi.models.create_invoice_response_data.CreateInvoiceResponse_data(
                    id = '', 
                    subtotal = 1.337, 
                    tax_amount = 1.337, 
                    total = 1.337, 
                    status = '', ),
                meta = ecuapi.models.meta.Meta(
                    request_id = '', 
                    timestamp = '', 
                    page = 1.337, 
                    per_page = 1.337, 
                    total = 1.337, 
                    total_pages = 1.337, ),
        )
        """

    def testCreateInvoiceResponse(self):
        """Test CreateInvoiceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
