# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_get(self) -> None:
        """Test case for health_get

        Basic health check
        """
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Detailed health check
        """
        pass

    def test_v1_health_get(self) -> None:
        """Test case for v1_health_get

        Basic health check
        """
        pass

    def test_v1_health_health_get(self) -> None:
        """Test case for v1_health_health_get

        Detailed health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
