# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.certificate_upload_response_meta import CertificateUploadResponseMeta

class TestCertificateUploadResponseMeta(unittest.TestCase):
    """CertificateUploadResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CertificateUploadResponseMeta:
        """Test CertificateUploadResponseMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CertificateUploadResponseMeta`
        """
        model = CertificateUploadResponseMeta()
        if include_optional:
            return CertificateUploadResponseMeta(
                request_id = '',
                timestamp = ''
            )
        else:
            return CertificateUploadResponseMeta(
                request_id = '',
                timestamp = '',
        )
        """

    def testCertificateUploadResponseMeta(self):
        """Test CertificateUploadResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
