# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ecuapi.models.create_invoice_request import CreateInvoiceRequest

class TestCreateInvoiceRequest(unittest.TestCase):
    """CreateInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInvoiceRequest:
        """Test CreateInvoiceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInvoiceRequest`
        """
        model = CreateInvoiceRequest()
        if include_optional:
            return CreateInvoiceRequest(
                customer = ecuapi.models.customer.Customer(
                    id = '1234567890001', 
                    id_type = 'ruc', 
                    name = 'Empresa Demo S.A.', 
                    email = 'cliente@example.com', 
                    address = 'Av. Principal 123', ),
                items = [
                    ecuapi.models.invoice_item.InvoiceItem(
                        code = 'PROD001', 
                        description = 'Servicio de consultoría', 
                        quantity = 1, 
                        unit_price = 10000, 
                        discount = 0, 
                        tax_code = '2', )
                    ],
                payment_method = '01',
                notes = 'Factura por servicios'
            )
        else:
            return CreateInvoiceRequest(
                customer = ecuapi.models.customer.Customer(
                    id = '1234567890001', 
                    id_type = 'ruc', 
                    name = 'Empresa Demo S.A.', 
                    email = 'cliente@example.com', 
                    address = 'Av. Principal 123', ),
                items = [
                    ecuapi.models.invoice_item.InvoiceItem(
                        code = 'PROD001', 
                        description = 'Servicio de consultoría', 
                        quantity = 1, 
                        unit_price = 10000, 
                        discount = 0, 
                        tax_code = '2', )
                    ],
        )
        """

    def testCreateInvoiceRequest(self):
        """Test CreateInvoiceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
