# coding: utf-8

"""
    ECUAPI - Electronic Invoicing API

    API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ecuabyte.lat
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Customer(BaseModel):
    """
    Customer
    """ # noqa: E501
    id: Annotated[str, Field(min_length=10, strict=True, max_length=13)] = Field(description="RUC, Cédula, or Passport")
    id_type: StrictStr = Field(alias="idType")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=300)]
    email: Optional[StrictStr] = None
    address: Optional[Annotated[str, Field(strict=True, max_length=300)]] = None
    phone: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    __properties: ClassVar[List[str]] = ["id", "idType", "name", "email", "address", "phone"]

    @field_validator('id_type')
    def id_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ruc', 'cedula', 'passport', 'final']):
            raise ValueError("must be one of enum values ('ruc', 'cedula', 'passport', 'final')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Customer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Customer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "idType": obj.get("idType"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "address": obj.get("address"),
            "phone": obj.get("phone")
        })
        return _obj


